apiVersion: v1
kind: Service
metadata:
  name: "{{ application_playbooks[application.key].vars.service_name }}"
spec:
  clusterIP: None  # Required for stable DNS with StatefulSets
  selector:
    app: postgres
  ports:
    - port: "{{ application_playbooks[application.key].vars.service_port }}"
      targetPort: "{{ application_playbooks[application.key].vars.service_port }}"
