apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ kustom.name }}
spec:
  schedule: "*/5 * * * *" # Runs every 5 minutes
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ kustom.name }}
        spec:
          serviceAccountName: {{ kustom.name }}
          restartPolicy: OnFailure
          securityContext:
            fsGroup: {{ kustom.security.runAsGroup }}
          containers:
          - name: tester
            env:
            - name: STORAGE_DRIVER
              value: vfs
            - name: APISERVER
              value: https://kubernetes.default.svc
            - name: CONTAINER_SSHKEY
              value: /tmp/home/.ssh/key
            - name: HOME
              value: /tmp/home
            - name: PODMAN_SSH_OPTS
              value: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
            - name: CONTAINER_HOST
              value: ssh://podman@10.10.10.10/run/podman/podman.sock
            - name: SERVICEACCOUNT
              value: /var/run/secrets/kubernetes.io/serviceaccount
            - name: ANSIBLE_STDOUT_CALLBACK
              value: default
            - name: ANSIBLE_CALLBACK_ENABLED
              value: simple_junit
            - name: ANSIBLE_RESULT_FORMAT
              value: yaml
            - name: JUNIT_OUTPUT_DIR
              value: /tmp/molecule
            - name: ANSIBLE_REMOTE_TMP
              value: /tmp/ansible
            - name: ANSIBLE_ASYNC_DIR
              value: /tmp/.ansible_async
            - name: ANSIBLE_CALLBACK_PLUGINS
              value: /tmp/home/home-cluster-deployment/callback_plugins
            image: {{ kustom.image }}
            command:
            - /bin/sh
            - -c
            - |
              # run molecule
              set -x
              mkdir -p $HOME/.ssh
              cp /tmp/.ssh/* $HOME/.ssh
              chmod 400 $HOME/.ssh/*
              rm $HOME/.ssh/known_hosts
              cd $HOME
              git clone --depth 1 --single-branch --recursive https://github.com/cainam/home-cluster-deployment.git
              cat >> molecule.yaml <<EOF
              ---
              dependency:
                name: galaxy
                enabled: false
              
              driver:
                name: podman
                options:
                  managed: true
              platforms:
                - name: instance
                  image: myregistry.adm13:443/local/molecule-tester:20260416
                  etc_hosts:
                    "molecule-instance": "127.0.0.1"
                  pre_build_image: true
                  network: host
                  security_opts:
                    - seccomp=unconfined
              provisioner:
                name: ansible
                config_options:
                  defaults:
                    fact_caching: jsonfile
                    fact_caching_connection: /tmp/ansible_cache
                    gather_facts: true
                    # Ensures the engine knows to load the junit plugin
                    callbacks_enabled: junit
              verifier:
                name: ansible
              EOF
              NAMESPACE=$(cat ${SERVICEACCOUNT}/namespace)
              TOKEN=$(cat ${SERVICEACCOUNT}/token)
              TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

              cd home-cluster-deployment/roles/shared_helper/

              /py_env/bin/python -m molecule  --base-config ${HOME}/molecule.yaml create --scenario-name test_directory_sync
              /py_env/bin/python -m molecule  --base-config ${HOME}/molecule.yaml converge --scenario-name test_directory_sync
              /py_env/bin/python -m molecule  --base-config ${HOME}/molecule.yaml verify --scenario-name test_directory_sync

              VALUE=$(cat /tmp/molecule/results.yaml)
              DATA="{\"metadata\":{\"annotations\":{"last_start":"${TIMESTAMP}","${VALUE//\"/\\\"}"}}}"
              PAYLOAD=$(cat <<EOF
              {
                "metadata": {
                  "annotations": {
                    "last_start": "${TIMESTAMP}",
                    "tests": "$(echo $VALUE | sed 's/"/\\"/g')"
                  }
                }
              }
              EOF
              )
              # patch the configmap
              curl --cacert "${SERVICEACCOUNT}/ca.crt" -X PATCH -H "Authorization: Bearer ${TOKEN}" -H "Content-Type: application/merge-patch+json" \
                   --data "${PAYLOAD}" "${APISERVER}/apis/batch/v1/namespaces/${NAMESPACE}/cronjobs/{{ kustom.name }}"
              #while sleep 99; do true; done
            securityContext:
              runAsUser: {{ kustom.security.runAsUser }}
              runAsGroup: {{ kustom.security.runAsGroup }}
            volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: ssh-auth
              mountPath: /tmp/.ssh
              readOnly: true
            - name: etc
              mountPath: /etc/passwd
              subPath: etc-passwd
            - name: etc
              mountPath: /etc/group
              subPath: etc-group
            - name: etc
              mountPath: /etc/subuid
              subPath: etc-subuid
            - name: etc
              mountPath: /etc/subgid
              subPath: etc-subgid
          volumes:
          - name: tmp
            emptyDir: {}
          - name: ssh-auth
            secret:
              secretName: {{ kustom.name }}
              defaultMode: 0400
          - name: etc
            configMap:
              name: {{ kustom.name }}
