apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ kustom.name }}
spec:
  schedule: "*/5 * * * *" # Runs every 5 minutes
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ kustom.name }}
        spec:
          serviceAccountName: {{ kustom.name }}
          restartPolicy: OnFailure
          containers:
          - name: checker
            image: {{ kustom.image }}
            command:
            - /bin/sh
            - -c
            - |
              # run molecule
              set -x
              TEST_NAME="foo"
              STATUS="bar"
              TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
              VALUE="{\"status\":\"$STATUS\",\"time\":\"$TIMESTAMP\"}"

              /py_env/bin/python -m molecule  --base-config /home/test_user/home-cluster-deployment/molecule.yaml test --scenario-name test_directory_sync

              APISERVER="https://kubernetes.default.svc"
              SERVICEACCOUNT="/var/run/secrets/kubernetes.io/serviceaccount"
              NAMESPACE=$(cat ${SERVICEACCOUNT}/namespace)
              TOKEN=$(cat ${SERVICEACCOUNT}/token)
              CACERT=${SERVICEACCOUNT}/ca.crt

              DATA="{\"metadata\":{\"annotations\":{\"$TEST_NAME\":\"${VALUE//\"/\\\"}\"}}}"
              # patch the configmap
              #curl --cacert "${CACERT}" -X PATCH -H "Authorization: Bearer ${TOKEN}" -H "Content-Type: application/merge-patch+json" \
              #     --data "${DATA}" "${APISERVER}/apis/batch/v1/namespaces/${NAMESPACE}/cronjobs/{{ kustom.name }}"
              podman run -it --rm myregistry.adm13:443/local/base busybox echo 'yaih!'
            volumeMounts:
            - name: varlibcontainers
              mountPath: /var/lib/containers
            - name: tun
              mountPath: /dev/net/tun
          volumes:
          - name: tun
            hostPath:
              path: /dev/net/tun
          - name: varlibcontainers
            emptyDir: {}
