apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ kustom.name }}
spec:
  schedule: "*/5 * * * *" # Runs every 5 minutes
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ kustom.name }}
        spec:
          serviceAccountName: {{ kustom.name }}
          restartPolicy: OnFailure
          securityContext:
            fsGroup: {{ kustom.security.runAsGroup }}
          containers:
          - name: tester
            env:
            - name: STORAGE_DRIVER
              value: vfs
            - name: APISERVER
              value: https://kubernetes.default.svc
            - name: CONTAINER_SSHKEY
              value: /tmp/home/.ssh/key
            - name: HOME
              value: /tmp/home
            - name: PODMAN_SSH_OPTS
              value: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
            - name: CONTAINER_HOST
              value: ssh://podman@10.10.10.10/run/podman/podman.sock
            - name: SERVICEACCOUNT
              value: /var/run/secrets/kubernetes.io/serviceaccount
            image: {{ kustom.image }}
            command:
            - /bin/sh
            - -c
            - |
              # run molecule
              set -x
              mkdir -p $HOME/.ssh
              cp /tmp/.ssh/* $HOME/.ssh
              chmod 400 $HOME/.ssh/*
              rm $HOME/.ssh/known_hosts
              cd $HOME
              git clone --depth 1 --single-branch --recursive https://github.com/cainam/home-cluster-deployment.git
              cd home-cluster-deployment/roles/shared_helper/

              TEST_NAME="foo"
              STATUS="bar"
              TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
              VALUE="{\"status\":\"$STATUS\",\"time\":\"$TIMESTAMP\"}"

              /py_env/bin/python -m molecule  --base-config /home/test_user/home-cluster-deployment/molecule.yaml test --scenario-name test_directory_sync

              NAMESPACE=$(cat ${SERVICEACCOUNT}/namespace)
              TOKEN=$(cat ${SERVICEACCOUNT}/token)

              #DATA="{\"metadata\":{\"annotations\":{\"$TEST_NAME\":\"${VALUE//\"/\\\"}\"}}}"
              DATA=$(cat /tmp/molecule/results.yaml)
              # patch the configmap
              curl --cacert "${SERVICEACCOUNT}/ca.crt" -X PATCH -H "Authorization: Bearer ${TOKEN}" -H "Content-Type: application/merge-patch+json" \
                   --data "${DATA}" "${APISERVER}/apis/batch/v1/namespaces/${NAMESPACE}/cronjobs/{{ kustom.name }}"
              while sleep 99; do true; done
            securityContext:
              allowPrivilegeEscalation: true
              runAsUser: {{ kustom.security.runAsUser }}
              runAsGroup: {{ kustom.security.runAsGroup }}
              seccompProfile:
                type: RuntimeDefault
              #  type: Localhost
              #  localhostProfile: podman.json
              capabilities:
                add: ["SETUID","SETGID","SYS_ADMIN"]
            volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: varlibcontainers
              mountPath: /var/lib/containers
            - name: tun
              mountPath: /dev/net/tun
            - name: {{ kustom.name }}-certs
              mountPath: /etc/certs
              readOnly: true
            - name: etc
              mountPath: /etc/passwd
              subPath: etc-passwd
            - name: etc
              mountPath: /etc/group
              subPath: etc-group
            - name: etc
              mountPath: /etc/subuid
              subPath: etc-subuid
            - name: etc
              mountPath: /etc/subgid
              subPath: etc-subgid
            - name: ssh-auth
              mountPath: /tmp/.ssh
              readOnly: true
          volumes:
          - name: tmp
            emptyDir: {}
          - name: varlibcontainers
            emptyDir: {}
          - name: tun
            hostPath:
              path: /dev/net/tun
          - name: {{ kustom.name }}-certs
            configMap:
              name: {{ kustom.name }}-certs
          - name: etc
            configMap:
              name: {{ kustom.name }}
          - name: ssh-auth
            secret:
              secretName: {{ kustom.name }}
              defaultMode: 0400
