namespace: {{ kustom.namespace }}

resources:
- CronJob.yaml
- RoleBinding.yaml
- Role.yaml
- ServiceAccount.yaml

configMapGenerator:
- name: {{ kustom.name }}-certs
  literals:
  - |
    service-ca-bundle.crt={{ application_playbooks[application.key].vars.ca_bundle | indent(4) }}

- name: {{ kustom.name }}
  literals:
  - etc-passwd="{{ kustom.name }}:x:{{ kustom.security.runAsUser }}:{{ kustom.security.runAsGroup }}:,,,:/home/myuser:/bin/bash"
  - etc-group="{{ kustom.name }}:x:{{ kustom.security.runAsGroup }}:"
  - etc-subuid="{{ kustom.name }}:100000:65536"
  - etc-subgid="{{ kustom.name }}:100000:65536"


secretGenerator:
- name: {{ kustom.name }}
  literals:
  - |
    key="{{ ssh_keys.podman.key | indent(4) }}"
    known_hosts="      {% for i in ssh_keys.hosts %}
      {{i~' ssh-'~ssh_keys.hosts[i].type~' '~ssh_keys.hosts[i].public}}
      {{(i| split('.') | first)~' ssh-'~ssh_keys.hosts[i].type~' '~ssh_keys.hosts[i].public}}
      {% if hostvars[i].alt_names is defined %}
      # alt_names is defined
      {% for j in hostvars[i].alt_names %}
      {{j~' ssh-'~ssh_keys.hosts[i].type~' '~ssh_keys.hosts[i].public}}
      {% endfor %}
      {% endif %}
      {% endfor %}"

generatorOptions:
  disableNameSuffixHash: true
  defaultMode: 0400
