namespace: {{ kustom.namespace }}
resources:
- clusterrolebinding.yaml
- clusterrole.yaml
- deploy.yaml
- service.yaml
- serviceaccount.yaml

secretGenerator:
- name: {{ kustom.name }}
  literals:
  - |
    flows_private.pem={{ api_keys.flows.private | indent(4) }}
    etcd_ca.crt={{ etcd.cert.crt }}
    etcd_client.crt={{ etcd.client.crt }}
    etcd_client.key={{ etcd.client.key }}

configMapGenerator:
- name: {{ kustom.name }}-certs
  literals:
  - |
    service-ca-bundle.crt={{ application_playbooks[application.key].vars.ca_bundle | indent(4) }}

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: service-ports.yaml
    target:
      kind: Service
      name: {{ kustom.name }}
