namespace: {{ kustom.namespace }}
resources:
- clusterrolebinding.yaml
- clusterrole.yaml
- deploy.yaml
- service.yaml
- serviceaccount.yaml

secretGenerator:
- name: {{ kustom.name }}
  literals:
  - |
    flows_private.pem={{ api_keys.flows.private | indent(4) }}
  - |
    etcd_ca.crt={{ etcd.cert.crt | indent(4) }}
  - |
    etcd_client.crt={{ etcd.client.crt | indent(4) }}
  - |
    etcd_client.key={{ etcd.client.key | indent(4) }}

configMapGenerator:
- name: {{ kustom.name }}
  literals:
  - |
    service-ca-bundle.crt={{ application_playbooks[application.key].vars.ca_bundle | indent(4) }}
  - control_plane_ips={% set ips = [] %}{% for h in groups['all'] if hostvars[h]['system_roles'] is defined and 'control_plane' in hostvars[h]['system_roles'] %}{% do ips.append(hostvars[h]['ansible_host'] | default(h)) %}{% endfor %}{{ ips | join(',') }}

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: service-ports.yaml
    target:
      kind: Service
      name: {{ kustom.name }}
