namespace: {{ kustom.namespace }}
resources:
- clusterrolebinding.yaml
- clusterrole.yaml
- deploy.yaml
- service.yaml
- serviceaccount.yaml

secretGenerator:
- name: {{ kustom.name }}
  literals:
  - |
    flows_private.pem={{ api_keys.flows.private | indent(4) }}
  - |
    etcd_ca.crt={{ etcd.cert.crt | indent(4) }}
  - |
    etcd_client.crt={{ etcd.client.crt | indent(4) }}
  - |
    etcd_client.key={{ etcd.client.key | indent(4) }}

{% set cp_ips = [] %}
{% for host in groups['all'] %}
{%   if 'control_plane' in (hostvars[host].system_roles | default([])) %}
{%     set _ = cp_ips.append(hostvars[host].ansible_host | default(hostvars[host].ansible_default_ipv4.address | default(host))) %}
{%   endif %}
{% endfor %}
configMapGenerator:
- name: {{ kustom.name }}
  literals:
  - |
    service-ca-bundle.crt={{ application_playbooks[application.key].vars.ca_bundle | indent(4) }}
  - control-plane-ips={{ cp_ips | join(',') }}

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: service-ports.yaml
    target:
      kind: Service
      name: {{ kustom.name }}
