images:
- name: bazel
  section: local
  requires:
  - base
  type: gentoo-image-builder
  env:
    JAVA_HOME: /opt/zulu
    USER: root
  build:
    packages: app-arch/zip
    configure_builder: emerge app-arch/zip
    finish_rootfs_build: |
      # https://cdn.azul.com/zulu/bin/zulu25.32.17-ca-jdk25.0.2-linux_musl_aarch64.tar.gz
      zulu=zulu21.48.17-ca-jdk21.0.10-linux_musl_aarch64.tar.gz
      ZULU_DIR=/opt/zulu
      curl -O https://cdn.azul.com/zulu/bin/$zulu
      mkdir -p "${ZULU_DIR}" && tar --directory "${ZULU_DIR}" --extract --strip-components=1 --file $zulu
      export JAVA_HOME=$ZULU_DIR
      export PATH=$JAVA_HOME/bin:$PATH

      bazel_version=8.6.0
      bazel_version=7.7.1

      bazel_dist=bazel-$bazel_version-dist.zip
      mkdir /bazel && cd bazel
      curl -L -O https://github.com/bazelbuild/bazel/releases/download/$bazel_version/$bazel_dist
      unzip -q $bazel_dist
      curl https://gitlab.alpinelinux.org/alpine/aports/-/raw/master/testing/bazel7/0001-off64t-fix.patch?ref_type=heads -O
      # bazel 7: curl https://gitlab.alpinelinux.org/alpine/aports/-/raw/master/testing/bazel7/0001-off64t-fix.patch?ref_type=heads -O
      # bazel 8: curl https://gitlab.alpinelinux.org/alpine/aports/-/raw/master/testing/bazel8/0001-off64t-fix.patch?ref_type=heads -O
      patch -p1 < 0001-off64t-fix.patch || true

      BAZEL_DEV_VERSION_OVERRIDE="${bazel_version}"  EXTRA_BAZEL_ARGS="--tool_java_runtime_version=local_jdk" bash ./compile.sh
      mkdir -p $ROOT/usr/local/bin
      cp -dp /bazel/output/bazel /usr/local/bin/

- name: envoy-base
  section: local
  requires:
  - bazel
  type: gentoo-image-builder
  build:
    packages: app-arch/zip
    configure_builder: |
      emerge llvm-core/clang llvm-runtimes/libcxx llvm-core/lld
      printf "%s static-libs\n" dev-libs/icu net-dns/c-ares app-arch/zstd net-libs/nghttp2 sys-libs/zlib >> /etc/portage/package.use/static-libs
      emerge -1v net-dns/c-ares app-arch/zstd sys-libs/zlib
      EXTRA_ECONF="--enable-static" emerge -v1 --usepkg=n net-libs/nghttp2
      export PATH=$(stat --printf="%n" /usr/lib/llvm/*/bin):$PATH
      export CC=clang
      export CXX=clang++
      export CONFIGURE="--prefix=/usr/local"
      export CXXFLAGS="-stdlib=libc++ -fPIC"
      export LDFLAGS="-stdlib=libc++"
      export LIBS="-lc++ -lc++abi"
      cd /var/tmp
      git clone --single-branch --depth 1 -b release-77-1 https://github.com/unicode-org/icu.git
      cd icu/icu4c/source/
      ./configure $CONFIGURE --enable-static --disable-shared --with-library-bits=64 --disable-samples --disable-tests # --disable-renaming
      make -j 3 && make install
      cd /var/tmp
      curl -OL https://github.com/libevent/libevent/releases/download/release-2.2.1-alpha/libevent-2.2.1-alpha-dev.tar.gz
      tar xfz libevent-2.2.1-alpha-dev.tar.gz
      cd libevent-2.2.1-alpha-dev; ./configure $CONFIGURE && make && make install
      cd /var/tmp
      git clone --single-branch --branch v2.1.ROLLING  --filter=blob:none https://luajit.org/git/luajit.git
      cd luajit/; make && make install
      for a in /usr/local/include/luajit-2.1/*; do ln -s $a /usr/local/include; done

- name: envoy
  section: local
  tag: "{{ software.istio.version }}"
  requires:
  - envoy-base
  type: gentoo-image-builder
  build:
    configure_builder: |
      cd /var/tmp; rm -rf * /root/.cache
      export JAVA_HOME=/opt/zulu
      export PATH=$(stat --printf="%n" /usr/lib/llvm/*/bin):${JAVA_HOME}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      export CC=$(which clang)
      git clone --depth 1 --single-branch -b {{ software.istio.version }} https://github.com/istio/proxy.git; cd proxy
      echo "build --define tcmalloc=disabled" >> .bazelrc
      mkdir -p tools/jdk/
      echo 'workspace(name = "local_jdk")' > tools/jdk/WORKSPACE
      cat > tools/jdk/BUILD.bazel <<'EOF'
      java_runtime(
          name = "local_jdk_runtime",
          java_home = "/opt/zulu",
          visibility = ["//visibility:public"],
      )
      
      toolchain(
          name = "bootstrap_runtime_toolchain_definition",
          toolchain = ":local_jdk_runtime",
          toolchain_type = "@bazel_tools//tools/jdk:bootstrap_runtime_toolchain_type",
          visibility = ["//visibility:public"],
      )
      
      toolchain(
          name = "runtime_toolchain_definition",
          toolchain = ":local_jdk_runtime",
          toolchain_type = "@bazel_tools//tools/jdk:runtime_toolchain_type",
          visibility = ["//visibility:public"],
      )
      EOF
      cat > add-pt1.txt <<'EOF'
            # Define the actual content once
      http_archive(
          name = "com_google_cel_spec",
          sha256 = "13583c5a312861648449845b709722676a3c9b43396b6b8e9cbe4538feb74ad2",
          strip_prefix = "cel-spec-0.25.1",
          urls = ["https://github.com/google/cel-spec/archive/v0.25.1.tar.gz"],
      )

      http_archive(
          name = "com_github_cncf_xds",
          sha256 = "82363065ca2c978398d2307fe960c301a0b6655d55981fac017783bba22771d9",
          strip_prefix = "xds-8bfbf64dc13ee1a570be4fbdcfccbdd8532463f0",
          urls = [ "https://storage.googleapis.com/grpc-bazel-mirror/github.com/cncf/xds/archive/8bfbf64dc13ee1a570be4fbdcfccbdd8532463f0.tar.gz",
                   "https://github.com/cncf/xds/archive/8bfbf64dc13ee1a570be4fbdcfccbdd8532463f0.tar.gz"],
          patch_cmds = [
              "sed -i 's/\"dev_cel\"/\"com_google_cel_spec\"/g' bazel/repository_locations.bzl",
              "sed -i 's/name = \"dev_cel\"/name = \"com_google_cel_spec\"/g' bazel/repositories.bzl",
              "find . -type f -name 'BUILD' -exec sed -i 's/@dev_cel/@com_google_cel_spec/g' {} +",
              "find . -type f -name '*.bzl' -exec sed -i 's/@dev_cel/@com_google_cel_spec/g' {} +",
              "find . -type f -name 'MODULE.bazel' -exec sed -i 's/@dev_cel/@com_google_cel_spec/g' {} +",
              "sed -i '/cel-spec/d' MODULE.bazel",
          ],
      )

      http_archive(
          name = "rules_python",
          sha256 = "f609f341d6e9090b981b3f45324d05a819fd7a5a56434f849c761971ce2c47da",
          strip_prefix = "rules_python-1.7.0",
          url = "https://github.com/bazel-contrib/rules_python/releases/download/1.7.0/rules_python-1.7.0.tar.gz",
          patch_cmds = [
          "sed -i '/\"3.12.12\": {/,/\"strip_prefix\"/ s/\"sha256\": {/&\\\n            \"aarch64-unknown-linux-musl\": \"1ea93c2ec158c3ede85e7123a2492a5d04e403ef2d924245f3e0e38276274779\",/' python/versions.bzl",
                  "sed -i '/platforms = {/a\\\n        \"aarch64-unknown-linux-musl\": platform_info(\\\n            compatible_with = [\\\n                \"@platforms//os:linux\",\\\n                \"@platforms//cpu:aarch64\",\\\n            ],\\\n            os_name = LINUX_NAME,\\\n            arch = \"aarch64\",\\\n        ),' python/versions.bzl",
                  ]
      )

      local_repository(
          name = "local_jdk",
          path = "tools/jdk",
      )

      register_toolchains(
          "@local_jdk//:bootstrap_runtime_toolchain_definition",
          "@local_jdk//:runtime_toolchain_definition",
      )

      register_toolchains("@toolchains_llvm//toolchain:all")
      EOF
      cat > add-pt2.txt <<'EOF'
          patch_cmds = [
      "sed -i 's/name = \"event\"/name = \"unused_event\"/' bazel/foreign_cc/BUILD",
              """printf '\ncc_library(
          name = "event",
          includes = ["/usr/local/include"],
          linkopts = ["-L/usr/local/lib", "-levent", "-levent_pthreads" ],
          visibility = ["//visibility:public"],
      )\n' >> bazel/foreign_cc/BUILD""",
          "sed -i 's/PYTHON_VERSION = \"[^\"]*\"/PYTHON_VERSION = \"3.12.12\"/' bazel/repositories_extra.bzl",
          ],
      EOF
      sed  -e '/repo:http/r add-pt1.txt' -e '/sha256 = ENVOY_SHA256,/r add-pt2.txt' -e '/llvm/d' -i WORKSPACE
      sed -i '/PATH/d' .bazelrc
      sed -e '/googleurl/d' -i envoy.bazelrc
      sed -e '/BAZEL_DO_NOT_DETECT_CPP_TOOLCH/d' -i envoy.bazelrc
      mkdir tools/cmake
      echo -e 'load("@rules_foreign_cc//toolchains/native_tools:native_tools_toolchain.bzl", "native_tool_toolchain")\nnative_tool_toolchain(
        name = "gentoo_cmake_resource",
        path = "/usr/bin/cmake",
        visibility = ["//visibility:public"],
      )
      \ntoolchain(
        name = "my_cmake_toolchain",
        exec_compatible_with = [
          "@platforms//os:linux",
          "@platforms//cpu:aarch64",  # Changed from x86_64 to aarch64
        ],
        toolchain = ":gentoo_cmake_resource",
        toolchain_type = "@rules_foreign_cc//toolchains:cmake_toolchain",
      )' > tools/cmake/BUILD
      bazel_options='--verbose_failures --strip=always --config=release --toolchain_resolution_debug=1 --copt=-Wno-error --java_runtime_version=local_jdk --tool_java_runtime_version=local_jdk --action_env=PATH='$PATH' --copt=-I/usr/local/include --copt=-Wno-sign-compare --copt=-Wno-error=deprecated-literal-operator --copt=-Wno-error=sign-compare --copt=-Wno-error=nullability-completeness --copt=-Wno-error --linkopt=-Wl,--no-gdb-index --host_linkopt=-static --linkopt=-static --host_linkopt=-Wl,--no-gdb-index --host_linkopt=-fuse-ld=lld --linkopt=-fuse-ld=lld --copt=-Wno-error --cxxopt=-Wno-error=unused-parameter --define=musl=true --host_linkopt=/usr/lib/libc.a  --linkopt=/usr/local/lib/libicui18n.a   --linkopt=/usr/local/lib/libicuuc.a --linkopt=/usr/local/lib/libicudata.a   --action_env=CMAKE=/usr/bin/cmake --repo_env=CMAKE=/usr/bin/cmake --define=lua=enabled --define=luajit=system --action_env=LUAJIT_LIB=/usr/local/lib   --action_env=LUAJIT_INCLUDE=/usr/local/include  --extra_toolchains=//tools/cmake:my_cmake_toolchain  --copt=-DFLATBUFFERS_LOCALE_INDEPENDENT=0 --copt=-Wno-error=nontrivial-memcall --stamp --subcommands --announce_rc --incompatible_enable_cc_toolchain_resolution=true    --cxxopt=--stdlib=libc++ --host_cxxopt=--stdlib=libc++ --linkopt=-lc++ --linkopt=-lc++abi --host_cxxopt=--stdlib=libc++ --host_linkopt=-lc++ --host_linkopt=-lc++abi '
      until bazel --output_user_root=$PWD/../cache fetch ${bazel_options}   -- //:envoy; do echo "retry in some seconds..."; sleep 5; done
      bazel  --output_user_root=$PWD/../cache build ${bazel_options} -- //:envoy
    finish_rootfs_build: |
      strip bazel-bin/envoy
      cp -dp bazel-bin/envoy  ${ROOT}/usr/local/bin/

- name: proxyv2
  section: istio-system
  tag: "{{ software.istio.version }}"
  requires:
  - envoy
  type: gentoo-image-builder
  build:
    entrypoint: ["/usr/local/bin/pilot-agent"]
    user: 1337
    configure_builder: |
      emerge dev-lang/go
    configure_rootfs_build: |
      git clone --depth 1 --single-branch -b {{ software.istio.version }}  https://github.com/istio/istio.git
      cd istio/pilot/cmd/pilot-agent
      CGO_ENABLED=0 go build -ldflags '-extldflags "-static" -s -w'
    finish_rootfs_build: |
      echo 'istio-proxy:x:1337:istio-proxy' > "${ROOT}/etc/group"
      echo 'istio-proxy:x:1337:1337:Linux User,,,:/home/istio-proxy:/bin/sh' > "${ROOT}/etc/passwd"
      mkdir -p "${ROOT}/usr/local/bin" && cp -dp pilot-agent "${ROOT}/usr/local/bin"
      mkdir -p "${ROOT}/var/lib/istio/envoy/" && cp -dp ../../../tools/packaging/common/envoy_bootstrap.json "${ROOT}/var/lib/istio/envoy/envoy_bootstrap_tmpl.json"
      rm -rf /root/go /root/.cache

- name: pilot
  tag: "{{ software.istio.version }}"
  section: istio-system
  type: gentoo-image-builder
  requires:
  - go
  build:
    entrypoint: ["/usr/local/bin/pilot-discovery"]
    user: 1337
    configure_rootfs_build: |
      cd /var/tmp
      git clone --depth 1 --single-branch -b {{ software.istio.version }} https://github.com/istio/istio.git
      cd istio/pilot/cmd/pilot-discovery
      CGO_ENABLED=0 go build -ldflags '-extldflags "-static" -s -w'
    finish_rootfs_build: |
      echo 'istio-proxy:x:1337:istio-proxy' > "${ROOT}/etc/group"
      echo 'istio-proxy:x:1337:1337:Linux User,,,:/home/istio-proxy:/bin/sh' > "${ROOT}/etc/passwd"
      mkdir -p "${ROOT}/usr/local/bin" && cp -dp pilot-discovery "${ROOT}/usr/local/bin"
      rm -rf /root/go /root/.cache

