apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ kustom.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ kustom.name }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - watch
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ kustom.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ kustom.name }}
subjects:
- kind: ServiceAccount
  name: {{ kustom.name }}
