images:
- name: oauth2-proxy
  section: auth
  type: gentoo-image-builder
  requires:
  - go
  build:
    entrypoint: ["/bin/oauth2-proxy"]
    configure_rootfs_build: |
      git clone -b "{{ software['oauth2-proxy'].version }}" https://github.com/oauth2-proxy/oauth2-proxy.git
      cd oauth2-proxy
      go build
      strip  oauth2-proxy
      mkdir -p "${ROOT}/bin"
      mv oauth2-proxy "${ROOT}/bin/"
      cd && rm -rf /oauth2-proxy /root/.??* /root/*


