apiVersion: v1
kind: ConfigMap
metadata:
  name: suricata-config
data:
  suricata.yaml: |
    %YAML 1.1
    ---
    vars:
      address-groups:
        HOME_NET: "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
        EXTERNAL_NET: "!$HOME_NET"

    default-log-dir: /var/log/suricata/

    # Outputs configuration
    outputs:
      - fast:
          enabled: true
          filename: fast.log
          append: true
      - eve-log:
          enabled: true
          filetype: regular
          filename: eve.json

    # Essential rule definitions
    default-rule-path: /var/lib/suricata/rules
    rule-files:
      - suricata.rules
---
apiVersion: v1
kind: Service
metadata:
  name: {{ kustom.name }}
spec:
  selector:
    app: api
  ports:
  - name: http
    port: 80
    targetPort: http
