apiVersion: apps/v1
kind: Deployment
metadata:
  name: fritzbox-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fritzbox-analyzer
  template:
    metadata:
      labels:
        app: fritzbox-analyzer
    spec:
      volumes:
        - name: suricata-logs
          emptyDir: {}
        - name: shared-pipe
          emptyDir: {}
        - name: suricata-config
          configMap:
            name: suricata-config
      securityContext:
        fsGroup: {{ kustom.security.runAsGroup }}

      containers:
        # --- Container 1: Fetcher (Fritz!Box HTTPS Stream) ---
        - name: stream-capture
          image: myregistry.adm13:443/local/shark:20260429
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -x
              TRAFFIC_FILTER="not (src net (10.0.0.0/8 or 172.16.0.0/12 or 192.168.0.0/16) and dst net (10.0.0.0/8 or 172.16.0.0/12 or 192.168.0.0/16))"
              IFACE="2-0"  # WAN
              IFACE="1-lan" # LAN
              #IFACE="internet"
              U1=$FRITZ_USER #$1
              P1=$FRITZ_PASS #$2
              OUT=$3
              SID='0000000000000000'

              valid_sid(){
                sid="$1"
                u="$2"
                p="$3"
                echo "Trying to login into $FRITZ_IP as user $u" >&2
                sid_status=$(curl -s "$FRITZ_IP/login_sid.lua?sid=${sid}" | awk -F'</?SID>' 'NF>1{print $2}')
                if [ ${sid_status} = '0000000000000000' ]; then
                  CHALLENGE=$(curl -k -s $FRITZ_IP/login_sid.lua |  grep -o "<Challenge>[a-z0-9]\{8\}" | cut -d'>' -f 2)
                  HASH=$(printf "%s-%s" "$CHALLENGE" "$p" | iconv -t UTF-16LE | md5sum | cut -d' ' -f1)
                  sid=$(curl -k -s "$FRITZ_IP/login_sid.lua" -d "response=$CHALLENGE-$HASH" -d 'username='${u} | grep -o "<SID>[a-z0-9]\{16\}" | cut -d'>' -f 2)
                  echo "${sid}" | grep ^0+$ && echo "Login failed. Did you create & use explicit Fritz!Box users?" >&2 && exit 1
                fi
                echo "${sid}"
              }
              
              echo "Capturing traffic on Fritz!Box interface $IFACE ..." 1>&2
              SID=$(valid_sid ${SID} $U1 $P1)
              curl -X POST "http://fritz.box/capture.lua" -d "sid=$SID" -d "capture=eth0" -d "stop=1"

              #[ -p /data/fritzpipe ] || mkfifo /data/fritzpipe
              #FILE=/data/fritzpipe
              mkdir /data/pcaps
              while sleep 5; do
                  #FILE="$OUT-$(date +%s).pcap"
                  FILE="/data/pcaps/fritz-$(date +%s).pcap"
                  SID=$(valid_sid ${SID} $U1 $P1)
                  URL="$FRITZ_IP/cgi-bin/capture_notimeout?ifaceorminor=$IFACE&snaplen=&capture=Start&sid=$SID"
                  #curl --no-buffer -s "$URL" --output $FILE # | podman run --rm -i -v /tmp:/tmp myregistry.adm13:443/local/shark:20260429 tcpdump -r - -w "$FILE" -C 10 -W 20 -G 60 -z gzip
                  #curl --no-buffer -s "$URL" > $FILE #| tcpdump -r - -w "$FILE" -C 1 "$TRAFFIC_FILTER"
                  #curl --no-buffer -s "$URL" --output "$FILE"
                  curl --no-buffer -v "$URL" | tcpdump -r - -w "$FILE" -C 1 
                  [ -f "$FILE" ] && [ ! -s "$FILE" ] && rm -fv "$FILE"
              done
          env:
            - name: FRITZ_IP
              value: "http://fritz.box"
            - name: FRITZ_USER
              valueFrom:
                secretKeyRef:
                  name: {{ kustom.name }}
                  key: username
            - name: FRITZ_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ kustom.name }}
                  key: password
          volumeMounts:
            - name: shared-pipe
              mountPath: /data

        # --- Container 2: Analyzer (Suricata IDS) ---
        - name: suricata-ids
          image: myregistry.adm13:443/local/suricata:20260521
          workingDir: /data
          command: ["/bin/sh", "-c"]
          args:
            - |
              #while [ ! -p /data/fritzpipe ]; do echo "Waiting for pipe..."; sleep 1; done
              while [ ! -d /data/pcap ]; do echo "Waiting for directory ..."; sleep 1; done
              while true; do
                echo "Suricata listening to pipe..."
                #suricata -r /data/fritzpipe -c /etc/suricata/suricata.yaml
                suricata --pcap-file-continuous -r /data/pcaps/ -c /etc/suricata/suricata.yaml
                echo "Pipe closed or Suricata restarted. Reloading in 2 seconds..."
                sleep 2
              done
          volumeMounts:
            - name: shared-pipe
              mountPath: /data
            - name: suricata-logs
              mountPath: /var/log/suricata
            - name: suricata-config
              mountPath: /etc/suricata/suricata.yaml
              subPath: suricata.yaml
