apiVersion: apps/v1
kind: Deployment
metadata:
  name: fritzbox-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fritzbox-analyzer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fritzbox-analyzer
    spec:
      shareProcessNamespace: true # this allows to access the process of suricata from another container
      securityContext:
        fsGroup: {{ kustom.security.runAsGroup }}
      volumes:
      - name: {{ kustom.name }}
        persistentVolumeClaim:
          claimName: {{ kustom.name }}
      - name: suricata-logs
        emptyDir: {}
      - name: shared-pipe
        emptyDir: {}
      - name: suricata-config
        configMap:
          name: suricata-config
      - name: {{ kustom.name }}-config
        configMap:
          name: {{ kustom.name }}
      containers:
        - name: stream-capture
          image: myregistry.adm13:443/local/shark:20260429
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -x
              TRAFFIC_FILTER="not (src net (10.0.0.0/8 or 172.16.0.0/12 or 192.168.0.0/16) and dst net (10.0.0.0/8 or 172.16.0.0/12 or 192.168.0.0/16))"
              IFACE="1-lan" # LAN IFACE="2-0"  # WAN #IFACE="internet"?
              SID='0000000000000000'
              valid_sid(){
                sid="$1"
                u="$2"
                p="$3"
                echo "Trying to login into $FRITZ_IP as user $u" >&2
                sid_status=$(curl -s "$FRITZ_IP/login_sid.lua?sid=${sid}" | awk -F'</?SID>' 'NF>1{print $2}')
                if [ ${sid_status} = '0000000000000000' ]; then
                  CHALLENGE=$(curl -k -s $FRITZ_IP/login_sid.lua |  grep -o "<Challenge>[a-z0-9]\{8\}" | cut -d'>' -f 2)
                  HASH=$(printf "%s-%s" "$CHALLENGE" "$p" | iconv -t UTF-16LE | md5sum | cut -d' ' -f1)
                  sid=$(curl -k -s "$FRITZ_IP/login_sid.lua" -d "response=$CHALLENGE-$HASH" -d 'username='${u} | grep -o "<SID>[a-z0-9]\{16\}" | cut -d'>' -f 2)
                  echo "${sid}" | grep ^0+$ && echo "Login failed. Did you create & use explicit Fritz!Box users?" >&2 && exit 1
                fi
                echo "${sid}"
              }
              echo "Capturing traffic on Fritz!Box interface $IFACE ..." 1>&2
              SID=$(valid_sid ${SID} $FRITZ_USER $FRITZ_PASS)
              curl -X POST "http://fritz.box/capture.lua" -d "sid=$SID" -d "capture=eth0" -d "stop=1"
              mkdir /data/pcaps
              while sleep 5; do
                FILE="/data/pcaps/fritz-$(date +%s).pcap"
                SID=$(valid_sid ${SID} $FRITZ_USER $FRITZ_PASS)
                URL="$FRITZ_IP/cgi-bin/capture_notimeout?ifaceorminor=$IFACE&snaplen=&capture=Start&sid=$SID"
                curl --no-buffer -v "$URL" | tcpdump -r - -w "$FILE" -C 1
                [ -f "$FILE" ] && [ ! -s "$FILE" ] && rm -fv "$FILE"
              done
          env:
            - name: FRITZ_IP
              value: "http://fritz.box"
            - name: FRITZ_USER
              valueFrom:
                secretKeyRef:
                  name: {{ kustom.name }}
                  key: username
            - name: FRITZ_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ kustom.name }}
                  key: password
          volumeMounts:
            - name: shared-pipe
              mountPath: /data
        - name: suricata-ids
          image: myregistry.adm13:443/local/suricata:20260521
          workingDir: /data
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /var/log/suricata/
              while [ ! -d /data/pcaps ]; do echo "Waiting for directory ..."; sleep 1; done
              while true; do
                echo "Suricata listening to pipe..."
                suricata --pcap-file-continuous -r /data/pcaps/ -c /etc/suricata/suricata.yaml -l /var/log/suricata/
                echo "Pipe closed or Suricata restarted. Reloading in 2 seconds..."
                sleep 2
              done
          volumeMounts:
          - name: shared-pipe
            mountPath: /data
          - name: {{ kustom.name }}
            mountPath: /var/log
        - name: process-suricata-alerts
          image: myregistry.adm13:443/local/python3:20260521
          command: ["python", "/app/{{ kustom.name }}.py"]
          volumeMounts:
          - mountPath: /app/{{ kustom.name }}.py
            name: {{ kustom.name }}-config
            subPath: process_suricata_alerts.py
          - name: {{ kustom.name }}
            mountPath: /var/log
