namespace: {{ kustom.namespace }}
resources:
- configmap_and_service.yaml
- deploy.yaml

secretGenerator:
- name: {{ kustom.name }}
  literals:
  - username={{ fritz[1].user }}
  - password={{ fritz[1].pass }}
  - openrouter={{ openrouter_api_key }}
  - abuseipdb={{ abuseipdb }}
  - groq={{ groq }}
  - urlhaus={{ urlhaus }}
  - flows_public.pem={{ api_keys.flows.public }}

configMapGenerator:
  - name: {{ kustom.name }}
    #behavior: replace
    files:
    - process_suricata_alerts.py
    - flow-information-collector.py
    - api.py

generatorOptions:
  disableNameSuffixHash: true

