namespace: {{ kustom.namespace }}
resources:
  - configmap.yaml
  - deploy.yaml

secretGenerator:
  - name: {{ kustom.name }}
    literals:
      - username={{ fritz[1].user }}
      - password={{ fritz[1].pass }}
      - openrouter={{ openrouter_api_key }}

configMapGenerator:
  - name: {{ kustom.name }}
    #behavior: replace
    files:
    - process_suricata_alerts.py
    - flow-information-collector.py
