apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ kustom.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ kustom.name }}
      app.kubernetes.io/name: {{ kustom.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ kustom.name }}
        app.kubernetes.io/name: {{ kustom.name }}
    spec:
      automountServiceAccountToken: true
      securityContext:
        fsGroup: {{ kustom.security.runAsGroup }}
      volumes:
      - name: log
        emptyDir: {}
      - name: config
        persistentVolumeClaim:
          claimName: {{ kustom.name }}
      containers:
      - name: {{ kustom.name }}
        command: ["/bin/sh", "-c"]
        args:
        - "python -m homeassistant --config /config --log-file /log/home-assistant.log"
        env:
        - name: PYTHONPATH
          value: /ha/core
        - name: PATH
          value: /py_env/bin:/bin:/usr/bin
        - name: T
          value: UTC
        image: {{ kustom.image }}
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8123
          timeoutSeconds: 1
        ports:
        - containerPort: 8123
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8123
          timeoutSeconds: 1
        resources: {}
        securityContext:
          runAsUser: {{ kustom.security.runAsUser }}
        startupProbe:
          failureThreshold: 30
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8123
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
        - name: log
          mountPath: /log
      initContainers:
      - command:
        - sh
        - -c
        - until pg_isready -h postgres.db -p 5432;do echo waiting for database; sleep
          2; done;
        image: "db/postgresql:{{ software['postgresql'].version }}"
        name: waitdb
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
